modLoader="javafml"
loaderVersion="[37,)"

license="MIT"
issueTrackerURL="https://github.com/VendoAU/MapTooltip/issues"

[[mods]]
modId="maptooltip"
version="${file.jarVersion}"
displayName="MapTooltip"
displayURL="https://www.curseforge.com/minecraft/mc-mods/map-tooltip"
logoFile="maptooltip.png"
authors="VendoAU"
description="View maps from your inventory"
